#整合flowable
flowable:
  #关闭定时任务JOB
  async-executor-activate: false
  #将databaseSchemaUpdate设置为true。当Flowable发现库与数据库表结构不一致时，会自动将数据库表结构升级至新版本。
  database-schema-update: true
  #自动部署时查找流程的目录
  process-definition-location-prefix: classpath*:/processes/
  app:
    enabled: true
  #案例处理
  cmmn:
    enabled: false
    #用户
  idm:
    enabled: false
    #决策表
  dmn:
    enabled: false
  add-sign:
    all-multi-layer: false   #是否允许多层加签

server:
  port: 9091
spring:
  profiles:
    include: database
    active: dev
  datasource:
    url: ${MYSQL_URL:jdbc:mysql://192.168.132.38:3309/flowable_test?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=GMT%2b8&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&nullCatalogMeansCurrent=true}
    username: ${MYSQL_USERNAME:ws}
    password: ${MYSQL_PASSWORD:unionmanws}
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 3
#    schema:
#      - classpath:sql/itbase.sql

mybatis:
  table:
    auto: create
  model:
    pack: com.example.flowable.domain

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
  mapper-locations: classpath*:mapper/*.xml

swagger:
  enable: true

doc:
  enable: true
project:
  name: IT基础框架

logging:
#  config: classpath:logback-spring.xml
#  file:
#    path: /data/home/umlinux/logs/itbase
  level:
    com.unionman: debug
    org.flowable: debug

